---
# make sure to install python
- hosts: all
  remote_user: root
  gather_facts: no
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal python-setuptools)

- hosts: all
  remote_user: root
  roles:
    - docker
