---

- module_defaults:
    hcloud_server:
      token: "{{ lookup('env','HCLOUD_TOKEN') | default(hetzner_token, true) }}"
      image: "{{ hetzner_instance_os }}"
      server_type: "{{ hetzner_instance_type }}"
      datacenter: "{{ hetzner_datacenter }}"
      ssh_keys: "{{ hetzner_ssh_keys }}"
  block:
    - hcloud_server:
        name: 'pwd.sva.hamburg'
        server_type: 'ccx51'
    - hcloud_server:
        name: 'training.sva.hamburg'
        server_type: 'cx31'


- name: Refresh inventory
  meta: refresh_inventory

- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: "pwd.sva.hamburg"
    search_regex: OpenSSH
    delay: 10

